#!/usr/bin/env python3
"""Create Windows-safe edit worksets for apply_patch and post-edit commands.

Purpose:
- Reduce PowerShell / Win32 command-line length by emitting one short path manifest.
- Split edit targets into conservative apply_patch-sized batches on Windows.
- Keep edit planning reproducible instead of relying on ad-hoc long path lists.

Usage:
    python -B scripts/summary/windows_edit_workset.py --paths AGENTS.md doc/WINDOWS_LENGTH_POLICY.md
    python -B scripts/summary/windows_edit_workset.py --paths scripts/summary/windows_edit_workset.py scripts/utils/windows_length_policy.py --label edit_plan
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.utils.windows_length_policy import (  # noqa: E402
    WINDOWS_SAFE_APPLY_PATCH_FILES_PER_BATCH,
    WINDOWS_SAFE_APPLY_PATCH_HEADER_LIMIT,
    compact_slug,
    estimate_apply_patch_header_chars,
    estimate_apply_patch_target_chars,
    expand_cli_paths,
    partition_paths_by_budget,
    write_path_manifest,
)


DEFAULT_OUT_DIR = ROOT / "output" / "private" / "summary" / "windows_worksets"
APPLY_PATCH_BASE_CHARS = len("*** Begin Patch\n") + len("*** End Patch\n")


# 関数: `_resolve_output_dir` の入出力契約と処理意図を定義する。
def _resolve_output_dir(raw_path: str) -> Path:
    """Resolve the manifest output directory against the repo root."""
    out_dir = Path(raw_path)
    if not out_dir.is_absolute():
        out_dir = (ROOT / out_dir).resolve()

    return out_dir


# 関数: `_batch_manifest_name` の入出力契約と処理意図を定義する。

def _batch_manifest_name(label_slug: str, batch_index: int) -> str:
    """Build one stable short filename for a patch batch manifest."""
    return f"{label_slug}_patch_{batch_index:02d}.txt"


# 関数: `parse_args` の入出力契約と処理意図を定義する。

def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Create Windows-safe path manifests and apply_patch workset batches."
    )
    parser.add_argument(
        "--paths",
        nargs="+",
        default=None,
        help="Target files/directories to include in the workset.",
    )
    parser.add_argument(
        "--paths-file",
        action="append",
        default=[],
        help=(
            "UTF-8 text file with one target path per line. Blank lines and lines starting with "
            "`#` are ignored; relative entries resolve against the manifest directory first and "
            "fall back to the repo root."
        ),
    )
    parser.add_argument(
        "--label",
        default="current_edit",
        help="Short label used in emitted manifest filenames (default: current_edit).",
    )
    parser.add_argument(
        "--out-dir",
        default=str(DEFAULT_OUT_DIR),
        help="Manifest output directory (default: output/private/summary/windows_worksets).",
    )
    parser.add_argument(
        "--max-files-per-batch",
        type=int,
        default=WINDOWS_SAFE_APPLY_PATCH_FILES_PER_BATCH,
        help=(
            "Maximum files per apply_patch-oriented batch "
            f"(default: {WINDOWS_SAFE_APPLY_PATCH_FILES_PER_BATCH})."
        ),
    )
    parser.add_argument(
        "--max-header-chars",
        type=int,
        default=WINDOWS_SAFE_APPLY_PATCH_HEADER_LIMIT,
        help=(
            "Conservative apply_patch header-character budget per batch "
            f"(default: {WINDOWS_SAFE_APPLY_PATCH_HEADER_LIMIT})."
        ),
    )
    return parser.parse_args()


# 関数: `main` の入出力契約と処理意図を定義する。

def main() -> int:
    """Create one all-path manifest plus one or more patch-batch manifests."""
    args = parse_args()
    target_paths = expand_cli_paths(args.paths, args.paths_file)
    if not target_paths:
        print("[fail] no target paths resolved.")
        return 1

    out_dir = _resolve_output_dir(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    label_slug = compact_slug(args.label, 40)

    all_manifest = write_path_manifest(
        out_dir / f"{label_slug}_all.txt",
        target_paths,
        header_lines=[
            f"generated by windows_edit_workset label={label_slug}",
            "use this manifest for post-edit formatter / audit commands",
        ],
    )
    patch_batches = partition_paths_by_budget(
        target_paths,
        max_entries=args.max_files_per_batch,
        max_chars=args.max_header_chars,
        base_chars=APPLY_PATCH_BASE_CHARS,
        item_weight=estimate_apply_patch_target_chars,
    )

    print(f"[summary] total_paths={len(target_paths)} all_manifest={all_manifest}")
    print(
        "[summary] patch_batches={batch_count} max_files_per_batch={file_cap} max_header_chars={char_cap}".format(
            batch_count=len(patch_batches),
            file_cap=args.max_files_per_batch,
            char_cap=args.max_header_chars,
        )
    )

    for batch_index, batch_paths in enumerate(patch_batches, start=1):
        manifest_path = write_path_manifest(
            out_dir / _batch_manifest_name(label_slug, batch_index),
            batch_paths,
            header_lines=[
                f"generated by windows_edit_workset batch={batch_index}",
                "default Windows rule: keep apply_patch worksets small",
            ],
        )
        estimated_header_chars = estimate_apply_patch_header_chars(batch_paths)
        print(
            "[batch] index={index} files={count} est_header_chars={chars} manifest={manifest}".format(
                index=batch_index,
                count=len(batch_paths),
                chars=estimated_header_chars,
                manifest=manifest_path,
            )
        )

    print(
        f"[next] python -B scripts/summary/enforce_python_block_spacing.py --paths-file {all_manifest} --fix"
    )
    print(
        f"[next] python -B scripts/summary/enforce_python_def_class_comments.py --paths-file {all_manifest} --fix"
    )
    return 0


# 条件分岐: `__name__ == \"__main__\"` を満たす経路を評価する。

if __name__ == "__main__":
    raise SystemExit(main())
